<template>
  <aside
    class="sidebar fixed top-20 bottom-0 lg:left-0 p-2 w-[300px] overflow-y-auto text-center bg-gray-900">
    <nav>
      <ul>
        <li>Eins</li>
        <li>Zwei</li>
        <li>Drei</li>
        <li>Vier</li>
        <li>Fünf</li>
        <li>Sechs</li>
        <li>Sieben</li>
        <li>Acht</li>
        <li>Neun</li>
        <li>Zehn</li>
      </ul>
    </nav>
  </aside>
</template>
